wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    code_path: code/main_ppo.py
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
